### ISSUE TITLE
Ability to reorder issues inside one column

### ISSUE THREAD

**Issue by pingvincible** [jgraichen/redmine_dashboard#243] opened 2022-05-30 08:56 UTC
**Is your feature request related to a problem? Please describe.**
Issues are always sorted by issue number. 

**Describe the solution you'd like**
I want to sort them by priority or in any way by drag'n'dropping them inside same column

**Comment by jgraichen** [comment] 2022-07-08 18:36
Duplicate of #125

**Closed by jgraichen** 2022-07-08 18:36 UTC
Labels: feature request
