### ISSUE TITLE
support the redmine context menu

### ISSUE THREAD

**Issue by yennor** [jgraichen/redmine_dashboard#143] opened 2020-05-26 21:46 UTC
It would be great if the redmine context menu appears when you right click on a ticket.
The way it also appears in the issue view.
I guess the integration should be possible, at least that plugin here integrates it:
https://github.com/happy-se-life/kanban

**Comment by jgraichen** [comment] 2021-07-17 09:27
Duplicate of #47

**Closed by jgraichen** 2021-07-17 09:27 UTC
Labels: contribution welcome, feature request
